### ISSUE TITLE
SaveMe tries to create a folder with the same name as the app itself

### ISSUE THREAD

**Issue by chazlarson** [kasiimh1/SaveMe#2]
OSX.

Default download is named "SaveMe".

When run, SaveMe tries to create a directory called "SaveMe" next to itself.  Since there is already a `/path/to/SaveMe`, it continues on and then fails to save the ticket.  Renaming the executable to something other than "SaveMe" works around it.

```
~/Downloads
➜ chmod a+x SaveMe

~/Downloads
➜ ./SaveMe


[*] Skipping creating SaveMe folder as it already exists
[*] Connect Device To Start..
[*] Press ENTER when Device is connected >
[*] Telling device with udid 00008020-001C1C510C41002E to enter recovery mode.
Device is successfully switching to recovery mode.
[*] Press ENTER when Device is in Recovery Mode >
[*] Detected A12(X) Device
[D] Device Model = iPhone11,8
[D] Device UDID = 00008020-001C1C510C41002E
[D] BoardConfig = N841AP
[D] ECID = 7912433771413550
[D] ApNonce = 462ce4bf03b478fb4556af4fcfa06feb8455dc1d1d1f998e2789aeba0036600c
[D] Enter the iOS version to save the ticket for > 12.4
Traceback (most recent call last):
  File "SaveMe.py", line 116, in <module>
NotADirectoryError: [Errno 20] Not a directory: '/Users/chazlarson/Downloads/SaveMe/7912433771413550'
[89253] Failed to execute script SaveMe
```

**Comment by kasiimh1** [comment]
Ohhh I can see the program the binary and folder and causing the error because they're named the same.

I forgot to mention to cd to ~Desktop on macOS instructions. 

Updated the instructions now

Simple fix for this would me to rename the files to 'SaveMe macOS' and 'SaveMe Windows' on the release page

**Comment by kasiimh1** [comment]
Fixed - Renamed the release files to:

SaveMe-macOS

SaveMe-Windows
